sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake libxtst-dev libx11-dev libjack-dev liblua5.2-dev --yes
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
